version: "3.8"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
networks:
  default:
    name: data-platform-network
    external: true

services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports: 
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
      - ./pyspark:/opt/workspace/pyspark
      - ../credentials:/opt/workspace/credentials
  spark-master:
    image: spark-master
    container_name: spark-master
    environment:
      SPARK_LOCAL_IP: 'spark-master'
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
      - ./pyspark:/opt/workspace/pyspark
      - ../credentials:/opt/workspace/credentials
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2g
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/opt/workspace
      - ./pyspark:/opt/workspace/pyspark
      - ../credentials:/opt/workspace/credentials
    depends_on:
      - spark-master
  spark-worker-2:
      image: spark-worker
      container_name: spark-worker-2
      environment:
        - SPARK_WORKER_CORES=1
        - SPARK_WORKER_MEMORY=2g
      ports:
        - 8084:8081
      volumes:
        - shared-workspace:/opt/workspace
        - ./pyspark:/opt/workspace/pyspark
        - ../credentials:/opt/workspace/credentials
      depends_on:
        - spark-master
